server.port: 10000

server.contextPath: /test

logging.config: classpath:config/logback.xml
logging.file: /home/test/Documents/log/paper.log

#spring.jpa.hibernate.ddl-auto: create
spring.datasource.url: jdbc:mysql://localhost:3306/test
spring.datasource.username: root
spring.datasource.password: root

spring.http.multipart.max-file-size: 1024MB
spring.http.multipart.max-request-size: 1024MB

upload.file.path: /home/test/Documents/paper
download.file.path: /home/test/Documents/paper/download/

#mail
workflowmanger.bpmn.smtphost: 10.69.0.123
workflowmanger.bpmn.smtpport: 25
workflowmanger.bpmn.emailfrom: roadDB_robot@ygomi.com
