### default config ###
server.port: 10000

server.contextPath: /test

#logging.config: classpath:config/logback.xml

#spring.jpa.hibernate.ddl-auto: create
spring.datasource.url: jdbc:mysql://localhost:3306/test
spring.datasource.username: root
spring.datasource.password: root

spring.http.multipart.max-file-size: 1024MB
spring.http.multipart.max-request-size: 1024MB

upload.file.path: /home/test/Documents/paper
download.file.path: /home/test/Documents/paper/download/

#mail
paper.smtphost: 10.69.0.123
paper.smtpport: 25
paper.emailfrom: roadDB_robot@ygomi.com

### production config ###
---
spring.profiles: production
#logging.file: /home/test/Documents/log/paper.log
